"""Update leave_request table

Revision ID: c0e1831a84ec
Revises: 5e377896e7fd
Create Date: 2026-03-12 21:48:04.731338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0e1831a84ec'
down_revision: Union[str, Sequence[str], None] = '5e377896e7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('leave_requests', 'start_date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.Date(),
    #            existing_nullable=False)
    # op.alter_column('leave_requests', 'end_date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.Date(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('leave_requests', 'end_date',
    #            existing_type=sa.Date(),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('leave_requests', 'start_date',
    #            existing_type=sa.Date(),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
